remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
plugins:
  - jekyll-remote-theme
baseurl: ''
lang: en-US
timezone: Asia/Ho_Chi_Minh
title: Programmer blog
tagline: Programmer blog
description: >-
  A minimal, portfolio, sidebar, bootstrap Jekyll theme with responsive web
  design and focuses on text presentation.
url: 'https://hardworklearner.github.io'
author: Hardwork đẹp trai
github:
  username: hardworklearner
twitter:
  username: twitter_username
social:
  name: Hardwork đẹp trai
  email: hardworklearner@gmail.com
  links:
    - 'https://twitter.com/username'
    - 'https://github.com/hardworklearner'
    - 'https://www.linkedin.com/in/hardwork-nguyen-75312a7b/'
google_site_verification: google_meta_tag_verification
google_analytics:
  id: G-S57T0PJRJG
  pv:
    enabled: false
    proxy_url: 'https://www.google-analytics.com'
    proxy_endpoint: 'https://www.google-analytics.com'
    cache: false
theme_mode: null
img_cdn: ''
avatar: assets/img/avatar.jpg
social_preview_image: null
toc: true
comments:
  active: null
  disqus:
    shortname: hardworklearner-github-io
  utterances:
    repo: null
    issue_term: null
  giscus:
    repo: null
    repo_id: null
    category: null
    category_id: null
    mapping: null
    input_position: null
    lang: null
    reactions_enabled: null
assets:
  self_host:
    enabled: null
    env: null
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths: null
paginate: 10
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
permalink: '/posts/:title/'
collections:
  tabs:
    output: true
    sort_by: order
languages:
  - vi
  - en
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: '/posts/:title/'
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ''
      type: tabs
    values:
      layout: page
      permalink: '/:title/'
  - scope:
      path: assets/js/dist
    values:
      swcache: true
sass:
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs:
      - development
plugins:
  - jekyll-admin
  - jekyll-seo-tag
exclude:
  - '*.gem'
  - '*.gemspec'
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: '/tags/:name/'
    category: '/categories/:name/'
# _config.yml
nav:
  - title: Home
    url: /
  - title: Portfolio
    url: /portfolio/
